# Generated by Django 3.0.2 on 2020-06-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0002_auto_20200626_0343'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='choice',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
