# Generated by Django 3.0.2 on 2020-07-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0003_auto_20200630_0843'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
